title: Michał Kalbarczyk Projects
author: Michał Kalbarczyk
description: Michał Kalbarczyk Projects
url: "https://projects.fazibear.me"
ga: "G-4093L52QLW"
nav_logo: projects.fazibear.me
primary_color: "#ff9462"

permalink: /:title/

visitors:
  path: fazibear.me
  label: "000000"
  count: "000000"

theme: "fazibear.me"

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  projects:
    output: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "terminal"
