title: Michał Kalbarczyk Projects
author: Michał Kalbarczyk
description: Michał Kalbarczyk Projects
url: "https://projects.fazibear.me"

permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
